# Generated by Django 5.2.3 on 2025-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='accuracy',
            field=models.FloatField(help_text='Typing accuracy in percentage'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='wpm',
            field=models.FloatField(help_text='Words per minute'),
        ),
    ]
