# Generated by Django 5.2.3 on 2025-08-14 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0002_alter_performance_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='paragraph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.TextField(help_text='The paragraph text for typing test'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
