# Generated by Django 5.2.3 on 2025-08-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0003_alter_performance_options_paragraph_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='errors',
            field=models.PositiveIntegerField(default=0, help_text='Number of typing errors'),
        ),
    ]
